ui:
  menu_limit: 5
authentication:
  header_path: headers
blend:
  default_length: 60
  filtering:
    blacklist_path: blacklists
    whitelist_path: whitelists
tracking:
  audits_path: tracking
automation:
  routines_path: routines.json
